package com.undabot.izzy

const val SINGLE_ARTICLE = "Article.json"
const val SINGLE_ARTICLE_WITH_LINKS = "article_with_links.json"
const val SINGLE_ARTICLE_WITH_COAUTHORS_META = "article_with_coauthors_meta.json"
const val SINGLE_ARTICLE_WITH_UNKNOWN_RESOURCE = "article_with_unknown_resource.json"
const val COLLECTION_ARTICLE_WITH_UNKNOWN_RESOURCE = "collection_article_with_unknown_resource.json"
const val COLLECTION_ARTICLE_WITH_LINKS = "collection_article_with_links.json"
const val COLLECTION_ARTICLE_WITH_COAUTHORS_META = "collection_article_with_coauthors_meta.json"
const val SINGLE_ARTICLE_WITHOUT_INCLUDED = "article_without_included.json"
const val COLLECTION_ARTICLE_WITHOUT_INCLUDED = "collection_article_without_included.json"
const val COLLECTION_ARTICLES = "Articles.json"
const val SINGLE_POLYMORPHIC = "DeserializerSinglePolymorphic.json"

const val NULL_LINKS = "null_links.json"
const val WITHOUT_LINKS = "document_without_links.json"
const val LINKS_WITH_NULL_VALUES = "links_with_null_values.json"
const val FULL_LINKS = "full_links.json"
const val DOCUMENT_WITH_LINKS = "document_with_links.json"
const val DOCUMENT_COLLECTION_WITH_LINKS = "document_collection_with_links.json"
const val INVALID_ROOT_ELEMENT = "invalid_root_element.json"
const val DOCUMENT_WITH_DATA_AND_ERRORS = "document_with_errors_and_data.json"
const val DOCUMENT_WITHOUT_TOP_LEVEL_MEMBERS = "document_without_top_level_members.json"
const val DOCUMENT_WITH_INCLUDED_AND_MISSING_DATA = "document_with_included_and_missing_data.json"
const val DOCUMENT_WITH_ERRORS = "document_with_errors.json"
const val DOCUMENT_WITH_META = "document_with_meta.json"
const val DOCUMENT_COLLECTION_WITH_META = "document_collection_with_meta.json"
const val COMPLEX_SINGLE_RESOURCE_DOCUMENT = "complex_single_resource_document.json"

const val PERSON_WITH_ARTICLE = "person_with_article.json"
const val PERSON_WITHOUT_ATTRIBUTES = "person_without_attributes.json"
const val SINGLE_ARTICLE_WITHOUT_INCLUDED_AND_META = "article_without_included_and_meta.json"
const val COLLECTION_OF_ARTICLES_ARTICLE_WITHOUT_INCLUDED_AND_META = "article_collection_without_included_and_meta.json"
